# Generated by Django 5.0.6 on 2026-01-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerreport',
            name='evidence_image',
            field=models.ImageField(max_length=500, upload_to='evidence_images/'),
        ),
    ]
