# Generated by Django 5.0.6 on 2026-01-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_sellerreport_evidence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='business_image/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='business_logo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images/'),
        ),
    ]
