# Generated by Django 5.0.6 on 2026-01-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='user_profiles'),
        ),
    ]
